return {
	Comment = { italic = true },
	Conditional = { italic = true },
	Function = { italic = true, bold = true },
	CursorLine = { bg = "#272b35" },
	CursorColumn = { bg = "#272b35" },

	NvimTreeOpenedFolderName = { bold = true, italic = true },
	NvimTreeOpenedFile = { bold = true, italic = true },

	Type = { italic = true },
	SpecialComment = { italic = true },
	TSConditional = { italic = true },
	TSAttribute = { italic = true },
	TSMethod = { italic = true },
	TSParameter = { italic = true },
	TSKeywordOperator = { italic = true },
	TSLabel = { italic = true },
	TSVariableBuiltin = { italic = true },
	TSTagAttribute = { italic = true },
	TSStrong = { bold = true, italic = true },
	TSEmphasis = { bold = true, italic = true },
	TSFunction = { bold = true, italic = true },
	TSUnderline = { underline = true },
}
