env:
  TERM: xterm-256color
scrolling:
  history: 10000
window:
  option_as_alt: Both
  padding:
    x: 2
    y: 0
  dynamic_title: true
  dynamic_padding: true
  scrolling:
    multiplier: 3
mouse:
  hints:
    mods: Command|Control
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true
draw_bold_text_with_bright_colors: true
custom_cursor_colors: true
font:
  size: 14.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  normal:
    family: PragmataProMonoLiga Nerd Font
    style: Regular
  bold:
    family: PragmataProMonoLiga Nerd Font
    style: Bold
  italic:
    family: PragmataProMonoLiga Nerd Font
    style: Italic
  bold_italic:
    family: PragmataProMonoLiga Nerd Font
    style: Bold Italic
key_bindings:
  # (Windows, Linux, and BSD only)
  - {key: V, mods: Control|Shift, action: Paste}
  - {key: C, mods: Control|Shift, action: Copy}
  - {key: Insert, mods: Shift, action: PasteSelection}
  - {key: Key0, mods: Control, action: ResetFontSize}
  - {key: Equals, mods: Control, action: IncreaseFontSize}
  - {key: Plus, mods: Control, action: IncreaseFontSize}
  - {key: Minus, mods: Control, action: DecreaseFontSize}
  - {key: F11, mods: None, action: ToggleFullscreen}
  - {key: Paste, mods: None, action: Paste}
  - {key: Copy, mods: None, action: Copy}
  - {key: L, mods: Control, action: ClearLogNotice}
  - {key: L, mods: Control, chars: "\f"}
  - {key: PageUp, mods: None, action: ScrollPageUp, mode: ~Alt}
  - {key: PageDown, mods: None, action: ScrollPageDown, mode: ~Alt}
  - {key: Home, mods: Shift, action: ScrollToTop, mode: ~Alt}
  - {key: End, mods: Shift, action: ScrollToBottom, mode: ~Alt}
# Colors (Yoru)
colors:
  # Default colors
  primary:
    background: '0x0c0e0f'
    foreground: '0xedeff0'
  cursor:
    text: '0x232526'
    cursor: '0xedeff0'
  vi_mode_cursor:
    text: '0x232526'
    cursor: '0xedeff0'
  selection:
    text: '0x0c0e0f'
    background: '0xbac1c5'
  # Normal colors
  normal:
    black: '0x232526'
    red: '0xdf5b61'
    green: '0x78b892'
    yellow: '0xde8f78'
    blue: '0x6791c9'
    magenta: '0xbc83e3'
    cyan: '0x67afc1'
    white: '0xe4e6e7'
  # Bright colors
  bright:
    black: '0x2c2e2f'
    red: '0xe8646a'
    green: '0x81c19b'
    yellow: '0xe79881'
    blue: '0x709ad2'
    magenta: '0xc58cec'
    cyan: '0x70b8ca'
    white: '0xf2f4f5'
