#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Added by `rbenv init` on Tue Jun 24 14:04:02 EDT 2025
eval "$(rbenv init - --no-rehash zsh)"
typeset -gU path
