# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -f ~/.fresh/build/shell.sh ]] && . ~/.fresh/build/shell.sh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Customize to your needs...
source ~/.zinit/bin/zinit.zsh

# Plugins
zinit light b4b4r07/enhancd
zinit light junegunn/fzf
zinit light Peltoche/lsd

# syntax, completions, suggestions
zinit wait lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma/fast-syntax-highlighting \
 blockf \
    zsh-users/zsh-completions \
 atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions

# z, z tab completion
zinit ice wait blockf lucid
zinit light rupa/z
zinit ice wait lucid
zinit light changyuheng/fz

# direnv
zinit as"program" make'!' atclone'./direnv hook zsh > zhook.zsh' \
  atpull'%atclone' pick"direnv" src"zhook.zsh" for \
  direnv/direnv

# dircolors
test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors)

# Misc
alias ls="exa"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=08'
export EDITOR='nvim'
unsetopt PATH_DIRS
