local packages = {
  "bash-language-server",
  "black",
  "clang-format",
  "clangd",
  "css-lsp",
  "eslint-lsp",
  "eslint_d",
  "goimports-reviser",
  "gopls",
  "html-lsp",
  "isort",
  "json-lsp",
  "lua-language-server",
  "prettierd",
  "protolint",
  "pyright",
  "rubyfmt",
  "rust-analyzer",
  "shellcheck",
  "shellharden",
  "shfmt",
  "sqlfluff",
  "stylelint-language-server",
  "stylua",
  "tailwindcss-language-server",
  "typescript-language-server",
  "unocss-language-server",
  "yaml-language-server",
  "yamlfmt",
  "yamllint",
}

return {
  ensure_installed = packages,
}
