-- nvim-treesitter `main` branch only takes `ensure_installed` (and `install_dir`).
-- Highlighting is enabled by NvChad's FileType autocmd that calls
-- `vim.treesitter.start()`. Folds/indents/incremental selection now come from
-- Neovim itself (see autocmds.lua).
return {
  ensure_installed = {
    "awk",
    "bash",
    "c",
    "cpp",
    "css",
    "dart",
    "dockerfile",
    "git_rebase",
    "gitcommit",
    "gitignore",
    "go",
    "graphql",
    "html",
    "javascript",
    "json",
    "json5",
    "lua",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    "ruby",
    "rust",
    "scss",
    "sql",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "vue",
    "yaml",
  },
}
