# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
os:
  copyToClipboardCmd: printf "\033]52;c;$(printf {{text}} | base64)\a" > /dev/tty
git:
  merging:
    args: '-no-ff'
  paging:
    colorArg: always
    pager: delta --dark --paging=never
